ALTER TABLE expenses ADD COLUMN IF NOT EXISTS color VARCHAR(10) DEFAULT NULL;
ALTER TABLE recurring_expenses ADD COLUMN IF NOT EXISTS currency VARCHAR(3) DEFAULT 'USD';
ALTER TABLE recurring_expenses ADD COLUMN IF NOT EXISTS amount_ars NUMERIC(14,2) DEFAULT NULL;
